### ISSUE TITLE
Could you update platformio release?

### ISSUE THREAD

**Issue by mdevaev** [Harvie/ps2dev#12]
https://libraries.io/platformio/ps2dev

**Comment by Harvie** [comment]
I did not added this library to platformio... I don't even know how it works. i think they periodicaly update everything themselves... Is there something i can do?

**Comment by mdevaev** [comment]
Platformio is a build system for controllers that is used by many large projects. For example, I use it even with Arduino instead of the Arduino IDE.

Although I never added libraries there and thought that the link was your own. I believe you need to register to add a library. If you find some time, it would be great if you added it. If not, thank you for your answer (and for your work), I will use the library directly from github.

**Comment by Harvie** [comment]
I know what platformio is. But i beleive they automaticaly download this library based on the fact it is included in the arduino repository... Why they didn't yet noticed the version v0.0.3 is unclear to me, because versions v0.0.1 and v0.0.2 they downloaded automaticaly without my help. Maybe there is some problem with library properties file? Or maybe they just take some time to re-scan libraries for updated versions...

https://github.com/Harvie/ps2dev/blob/master/library.properties

**Comment by mdevaev** [comment]
~~Try to add double quotes around paragraph value. Maybe it will help~~

Okay I dont see if any quotes acceptable in the spec... https://arduino.github.io/arduino-cli/library-specification/

**Comment by Harvie** [comment]
Adafruit does top quality libraries and they don't use quotes:
https://github.com/adafruit/Adafruit_NeoPixel/blob/master/library.properties

Also i wasn't problem before... Maybe the stuff became broken once i've added LICENSE file. But i beleive the MIT license is should be OK for platformio. Also they should have provide some warning if something is wrong in upstream... Maybe you should ask them...

If you go to the page https://libraries.io/platformio/ps2dev
There is link "Something wrong with this page? Make a suggestion"
Perhaps that will help you.

**Comment by Harvie** [comment]
It seems they updated it now. Maybe they just take some time before they download latest version...
